__version__ = "0.1.0"

from .db import DEFAULT_DB_PATH, _validate_identifier, _validate_qualified_name, get_connection
from .embeddings import (
    MODELS,
    fetch_category_texts,
    fetch_clue_texts,
    fetch_full_context_texts,
    fetch_response_texts,
    generate_category_embeddings,
    generate_clue_embeddings,
    generate_full_context_embeddings,
    generate_response_embeddings,
    get_embedding,
    load_model,
    save_embeddings,
    save_full_context_embeddings,
)
from .models import Category, Clue, Contestant, Episode, Round
from .scraping import (
    check_robots,
    delete_episode,
    ensure_schema,
    episode_url,
    fetch_episode,
    fetch_episodes,
    fetch_season,
    get_season_game_ids,
    list_episodes,
    list_seasons,
    load_episode,
    parse_episode,
    save_episode,
    season_url,
)

__all__ = [
    "Category",
    "Clue",
    "Contestant",
    "DEFAULT_DB_PATH",
    "Episode",
    "MODELS",
    "Round",
    "_validate_identifier",
    "_validate_qualified_name",
    "check_robots",
    "delete_episode",
    "ensure_schema",
    "episode_url",
    "fetch_category_texts",
    "fetch_clue_texts",
    "fetch_episode",
    "fetch_episodes",
    "fetch_full_context_texts",
    "fetch_response_texts",
    "fetch_season",
    "generate_category_embeddings",
    "generate_clue_embeddings",
    "generate_full_context_embeddings",
    "generate_response_embeddings",
    "get_connection",
    "get_embedding",
    "get_season_game_ids",
    "list_episodes",
    "list_seasons",
    "load_episode",
    "load_model",
    "parse_episode",
    "save_embeddings",
    "save_episode",
    "save_full_context_embeddings",
    "season_url",
]
